package Enums;

import model.Card;
import model.Unit;

public enum AllUnits {
    // units
    // all
    Dandelion(new Unit(null, "Dandelion", 2, 1, false, Type.CLOSE, Ability.COMMANDERS_HORN)),
    YenneferOfVengerberg(new Unit(null, "YenneferOfVengerberg", 7, 1, true, Type.RANGED, Ability.MEDIC)),
    OlgierdVonEverc(new Unit(null, "OlgierdVonEverc", 6, 1, false, Type.AGILE, Ability.MORAL_BOOST)),
    GaunterODimm(new Unit(null, "GaunterODimm", 2, 1, false, Type.SIEGE, Ability.MUSTER)),
    GaunterODImmDarkness(new Unit(null, "GaunterODImmDarkness", 4, 3, false, Type.RANGED, Ability.MUSTER)),
    Villentretenmerth(new Unit(null, "Villentretenmerth", 7, 1, false, Type.CLOSE, Ability.SCORCH)),
    MysteriousElf(new Unit(null, "MysteriousElf", 0, 1, true, Type.CLOSE, Ability.SPY)),
    Cow(new Unit(null, "Cow", 0, 1, false, Type.RANGED, Ability.TRANSFORMER)),
    EmielRegis(new Unit(null, "EmielRegis", 5, 1, false, Type.CLOSE, null)),
    GeraltOfRivia(new Unit(null, "GeraltOfRivia", 15, 1, true, Type.CLOSE, null)),
    TrissMerigold(new Unit(null, "TrissMerigold", 7, 1, true, Type.CLOSE, null)),
    Vesemir(new Unit(null, "Vesemir", 6, 1, false, Type.CLOSE, null)),
    ZoltanChivay(new Unit(null, "ZoltanChivay", 5, 1, false, Type.CLOSE, null)),
    // monsters
    Kayran(new Unit("Monsters", "Kayran", 8, 1, true, Type.AGILE, Ability.MORAL_BOOST)),
    Arachas(new Unit("Monsters", "Arachas", 4, 1, false, Type.CLOSE, Ability.MUSTER)),
    ArachasBehemoth(new Unit("Monsters", "ArachasBehemoth", 6, 1, false, Type.SIEGE, Ability.MUSTER)),
    Brewess(new Unit("Monsters", "Brewess", 6, 1, false, Type.CLOSE, Ability.MUSTER)),
    Weavess(new Unit("Monsters", "Weavess", 6, 1, false, Type.CLOSE, Ability.MUSTER)),
    Whispess(new Unit("Monsters", "Whispess", 6, 1, false, Type.CLOSE, Ability.MUSTER)),
    Ghoul(new Unit("Monsters", "Ghoul", 1, 3, false, Type.CLOSE, Ability.MUSTER)),
    Nekker(new Unit("Monsters", "Nekker", 2, 3, false, Type.CLOSE, Ability.MUSTER)),
    VampireBruxa(new Unit("Monsters", "VampireBruxa", 4, 1, false, Type.CLOSE, Ability.MUSTER)),
    VampireEkimmara(new Unit("Monsters", "VampireEkimmara", 4, 1, false, Type.CLOSE, Ability.MUSTER)),
    VampireFleder(new Unit("Monsters", "VampireFleder", 4, 1, false, Type.CLOSE, Ability.MUSTER)),
    VampireGarkain(new Unit("Monsters", "VampireGarkain", 4, 1, false, Type.CLOSE, Ability.MUSTER)),
    VampireKatakan(new Unit("Monsters", "VampireKatakan", 5, 1, false, Type.CLOSE, Ability.MUSTER)),
    Toad(new Unit("Monsters", "Toad", 7, 1, false, Type.RANGED, Ability.SCORCH)),
    Botchling(new Unit("Monsters", "Botchling", 4, 1, false, Type.CLOSE, null)),
    CelaenoHarpy(new Unit("Monsters", "CelaenoHarpy", 2, 1, false, Type.AGILE, null)),
    Cockatrice(new Unit("Monsters", "Cockatrice", 2, 1, false,Type.RANGED, null)),
    Draug(new Unit("Monsters", "Draug", 10, 1, true, Type.CLOSE, null)),
    EarthElemental(new Unit("Monsters", "EarthElemental", 6, 1, false, Type.SIEGE,null)),
    Endrega(new Unit("Monsters", "Endrega", 2, 1, false, Type.RANGED, null)),
    Fiend(new Unit("Monsters", "Fiend", 6, 1, false, Type.CLOSE, null)),
    FireElemental(new Unit("Monsters", "FireElemental", 6, 1, false, Type.SIEGE,null)),
    Foglet(new Unit("Monsters", "Foglet", 2, 1, false, Type.CLOSE, null)),
    Forktail(new Unit("Monsters", "Forktail", 5, 1, false, Type.CLOSE, null)),
    Frightener(new Unit("Monsters", "Frightener", 5, 1, false, Type.CLOSE, null)),
    Gargoyle(new Unit("Monsters", "Gargoyle", 2, 1, false, Type.RANGED, null)),
    GraveHag(new Unit("Monsters", "GraveHag", 5, 1, false, Type.RANGED, null)),
    Griffin(new Unit("Monsters", "Griffin", 5, 1, false, Type.CLOSE, null)),
    Harpy(new Unit("Monsters", "Harpy", 2,1, false, Type.AGILE, null)),
    IceGiant(new Unit("Monsters", "IceGiant", 5, 1, false,Type.SIEGE, null)),
    Imlerith(new Unit("Monsters", "Imlerith", 10, 1, true,Type.CLOSE, null)),
    Leshen(new Unit("Monsters", "Leshen", 10, 1, true, Type.CLOSE, null)),
    PlagueMaiden(new Unit("Monsters", "PlagueMaiden", 5, 1, false, Type.CLOSE, null)),
    Werewolf(new Unit("Monsters", "Werewolf", 5, 1, false, Type.CLOSE, null)),
    Wyvern(new Unit("Monsters", "Wyvern", 2,1,false, Type.RANGED, null)),
    // nilfgaardian Empire
    AssireVarAnahid(new Unit("NilfgaardianEmpire", "AssireVarAnahid", 6,1,false, Type.RANGED, null)),
    Albrich(new Unit("NilfgaardianEmpire", "Albrich", 6,1,false, Type.RANGED, null)),
    ImperaBrigadeGuard(new Unit("NilfgaardianEmpire", "ImperaBrigadeGuard", 3,4,false, Type.CLOSE,null)),
    StefanSkellen(new Unit("NilfgaardianEmpire","StefanSkellen",9,1,false,Type.CLOSE,null)),
    YoungEmissary(new Unit("NilfgaardianEmpire", "YoungEmissary",5,2,false,Type.CLOSE,null)),
    CahirMawrDyffrynAepCeallach(new Unit("NilfgaardianEmpire","CahirMawrDyffrynAepCeallach", 6,1,false,Type.CLOSE,null)),
    VattierDeRideaux(new Unit("NilfgaardianEmpire","VattierDeRideaux",4,1,false,Type.CLOSE,null)),
    Puttkammer(new Unit("NilfgaardianEmpire","Puttkammer",3,1,false,Type.RANGED,null)),
    LethoOfGulet(new Unit("NilfgaardianEmpire","LethoOfGulet",10,1,true,Type.CLOSE,null)),
    ShilardFitzOesterlen(new Unit("NilfgaardianEmpire","ShilardFitzOesterlen",7,1,false,Type.CLOSE,Ability.SPY)),
    BlackInfantryArcher(new Unit("NilfgaardianEmpire","BlackInfantryArcher",10,2,false,Type.RANGED,null)),
    TiborEggebracht(new Unit("NilfgaardianEmpire","TiborEggebracht",10,1,true,Type.RANGED,null)),
    RenualdAepMatsen(new Unit("NilfgaardianEmpire","RenualdAepMatsen",5,1,false,Type.RANGED,null)),
    Rainfarn(new Unit("NilfgaardianEmpire","Rainfarn",4,1,false,Type.CLOSE,null)),
    FringillaVigo(new Unit("NilfgaardianEmpire","FringillaVigo",6,1,false,Type.RANGED,null)),
    RottenMangonel(new Unit("NilfgaardianEmpire","RottenMangonel",3,1,false,Type.SIEGE,null)),
    ZerrikanianFireScorpion(new Unit("NilfgaardianEmpire","ZerrikanianFireScorpion",5,1,false,Type.SIEGE,null)),
    SiegeEngineer(new Unit("NilfgaardianEmpire","SiegeEngineer",6,1,false,Type.SIEGE,null)),
    MorvranVoorhis(new Unit("NilfgaardianEmpire","MorvranVoorhis",10,1,true,Type.SIEGE,null)),
    HeavyZerrikanianFireScorpion(new Unit("NilfgaardianEmpire","HeavyZerrikanianFireScorpion",10,1,false,Type.SIEGE,null)),
    Cynthia(new Unit("NilfgaardianEmpire","Cynthia",4,1,false,Type.RANGED,null)),
    EtolianAuxiliaryArchers(new Unit("NilfgaardianEmpire","EtolianAuxiliaryArchers",1,2,false,Type.RANGED,null)),
    MennoCoehoorn(new Unit("NilfgaardianEmpire","MennoCoehoorn",10,1,true,Type.CLOSE,null)),
    Morteisen(new Unit("NilfgaardianEmpire","Morteisen",3,1,false,Type.CLOSE,null)),
    NausicaaCavalryRider(new Unit("NilfgaardianEmpire","NausicaaCavalryRider",2,3,false,Type.CLOSE,null)),
    SiegeTechnician(new Unit("NilfgaardianEmpire","SiegeTechnician",0,1,false,Type.SIEGE,null)),
    Sweers(new Unit("NilfgaardianEmpire","Sweers",2,1,false,Type.RANGED,null)),
    Vanhemar(new Unit("NilfgaardianEmpire","Vanhemar",4,1,false,Type.RANGED,null)),
    Vreemde(new Unit("NilfgaardianEmpire","Vreemde",2,0,false,Type.CLOSE,null)),
    // northern realms
    Ballista(new Unit("NorthernRealms","Ballista",6,2,false,Type.SIEGE, null)),
    Catapult(new Unit("NorthernRealms","Catapult",8,2,false,Type.SIEGE,Ability.TIGHT_BOND)),
    DragonHunter(new Unit("NorthernRealms","DragonHunter",5,3,false,Type.RANGED,Ability.TIGHT_BOND)),
    Trebuchet(new Unit("NorthernRealms","Trebuchet",6,2,false,Type.SIEGE,null)),
    BlueStripesCommando(new Unit("NorthernRealms","BlueStripesCommando",4,3,false,Type.CLOSE,Ability.TIGHT_BOND)),
    Dethmold(new Unit("NorthernRealms","Dethmold",6,1,false,Type.RANGED,null)),
    KeiraMetz(new Unit("NorthernRealms","KeiraMetz",5,1,false,Type.RANGED,null)),
    SheldonSkaggs(new Unit("NorthernRealms","SheldonSkaggs",4,1,false,Type.RANGED,null)),
    DunBannerMedic(new Unit("NorthernRealms","DunBannerMedic",5,1,false,Type.SIEGE,Ability.MEDIC)),
    EsteradThyssen(new Unit("NorthernRealms","EsteradThyssen",10,1,true,Type.CLOSE,null)),
    JohnNatalis(new Unit("NorthernRealms","JohnNatalis",10,1,true,Type.CLOSE,null)),
    KaedweniSiegeExpert(new Unit("NorthernRealms","KaedweniSiegeExpert",1,3,false,Type.SIEGE,Ability.MORAL_BOOST)),
    PhilippaEilhart(new Unit("NorthernRealms","PhilippaEilhart",10,1,true,Type.RANGED,null)),
    PoorFuckingInfantry(new Unit("NorthernRealms","PoorFuckingInfantry",1,4,false,Type.CLOSE,Ability.TIGHT_BOND)),
    PrinceStennis(new Unit("NorthernRealms","PrinceStennis",5,1,false,Type.CLOSE,Ability.SPY)),
    RedanianFootSoldier(new Unit("NorthernRealms","RedanianFootSoldier",1,2,false,Type.CLOSE,null)),
    SabrinaGlevissing(new Unit("NorthernRealms","SabrinaGlevissing",4,1,false,Type.RANGED,null)),
    SiegeTower(new Unit("NorthernRealms","SiegeTower",6,1,false,Type.SIEGE,null)),
    SiegfriedOfDenesle(new Unit("NorthernRealms","SiegfriedOfDenesle",5,1,false,Type.CLOSE,null)),
    SigismundDijkstra(new Unit("NorthernRealms","SigismundDijkstra",4,1,false,Type.CLOSE,Ability.SPY)),
    SileDeTansarville(new Unit("NorthernRealms","SileDeTansarville",5,1,false,Type.RANGED,null)),
    Thaler(new Unit("NorthernRealms","Thaler",1,1,false,Type.SIEGE,Ability.SPY)),
    VernonRoche(new Unit("NorthernRealms","VernonRoche",10,1,true,Type.CLOSE,null)),
    Ves(new Unit("NorthernRealms","Ves",5,1,false,Type.CLOSE,null)),
    YarpenZirgrin(new Unit("NorthernRealms","YarpenZirgrin",2,1,false,Type.CLOSE,null)),
    // scoia'tael
    ElvenSkirmisher(new Unit("Scoiatael","ElvenSkirmisher",2,3,false,Type.RANGED,Ability.MUSTER)),
    Yaevinn(new Unit("Scoiatael","Yaevinn",6,1,false,Type.AGILE,null)),
    CiaranAep(new Unit("Scoiatael","CiaranAep",3,1,false,Type.AGILE,null)),
    DennisCranmer(new Unit("Scoiatael","DennisCranmer",6,1,false,Type.CLOSE,null)),
    DolBlathannaScout(new Unit("Scoiatael","DolBlathannaScout",6,3,false,Type.AGILE,null)),
    DolBlathannaArcher(new Unit("Scoiatael","DolBlathannaArcher",4,1,false,Type.RANGED,null)),
    DwarvenSkirmisher(new Unit("Scoiatael","DwarvenSkirmisher",3,3,false,Type.CLOSE,Ability.MUSTER)),
    HavekarHealer(new Unit("Scoiatael","HavekarHealer",0,3,false,Type.RANGED,Ability.MEDIC)),
    HavekarSmuggler(new Unit("Scoiatael","HavekarSmuggler",5,3,false,Type.CLOSE,Ability.MUSTER)),
    IdaEmeanAep(new Unit("Scoiatael","IdaEmeanAep",6,1,false,Type.RANGED,null)),
    Riordain(new Unit("Scoiatael","Riordain",1,1,false,Type.RANGED,null)),
    Toruviel(new Unit("Scoiatael","Toruviel",2,1,false,Type.RANGED,null)),
    VriheddBrigadeRecruit(new Unit("Scoiatael","VriheddBrigadeRecruit",4,1,false,Type.RANGED,null)),
    VriheddBrigadeVeteran(new Unit("Scoiatael","VriheddBrigadeVeteran",5,2,false,Type.AGILE,null)),
    Milva(new Unit("Scoiatael","Milva",10,1,false,Type.RANGED,Ability.MORAL_BOOST)),
    Seasenthessis(new Unit("Scoiatael","Seasenthessis",10,1,true,Type.RANGED,null)),
    Schirru(new Unit("Scoiatael","Schirru",8,1,false,Type.SIEGE,Ability.SCORCH)),
    Eithne(new Unit("Scoiatael","Eithne",10,1,true,Type.RANGED,null)),
    IsengrimFaoiltiarna(new Unit("Scoiatael","IsengrimFaoiltiarna",10,1,true,Type.CLOSE,Ability.MORAL_BOOST)),
    Filavandrel(new Unit("Scoiatael","Filavandrel",6,1,false,Type.AGILE,null)),
    BarclayEls(new Unit("Scoiatael","BarclayEls",6,1,false,Type.AGILE,null)),
    MahakamanDefender(new Unit("Scoiatael","MahakamanDefender",5,5,false,Type.CLOSE,null)),
    Iorveth(new Unit("Scoiatael","Iorveth",10,1,true,Type.RANGED,null)),
    // skellige
    Berserker(new Unit("Skellige","Berserker",4,1,false,Type.CLOSE,Ability.BERSERKER)),
    Vidkaarl(new Unit("Skellige","Vidkaarl",14,0,false,Type.CLOSE,Ability.MORAL_BOOST)),
    Svanrige(new Unit("Skellige","Svanrige",4,1,false,Type.CLOSE,null)),
    Udalryk(new Unit("Skellige","Udalryk",4,1,false,Type.CLOSE,null)),
    DonarAnHindar(new Unit("Skellige","DonarAnHindar",4,1,false,Type.CLOSE,null)),
    ClanAnCraite(new Unit("Skellige","ClanAnCraite",6,3,false,Type.CLOSE,Ability.TIGHT_BOND)),
    MadmanLugos(new Unit("Skellige","MadmanLugos",6,1,false,Type.CLOSE,null)),
    Cerys(new Unit("Skellige","Cerys",10,1,true,Type.CLOSE, Ability.MUSTER)),
    Kambi(new Unit("Skellige","Kambi",11,1,true,Type.CLOSE,Ability.TRANSFORMER)),
    BirnaBran(new Unit("Skellige","BirnaBran",2,1,false,Type.CLOSE,Ability.MEDIC)),
    ClanDrummondShieldmaiden(new Unit("Skellige","ClanDrummondShieldmaiden",4,3,false,Type.CLOSE,Ability.TIGHT_BOND)),
    ClanDimunPirate(new Unit("Skellige","ClanDimunPirate",6,1,false,Type.RANGED,Ability.SCORCH)),
    ClanBrokvarArcher(new Unit("Skellige","ClanBrokvarArcher",6,3,false,Type.RANGED,null)),
    Ermion(new Unit("Skellige","Ermion",8,1,true,Type.RANGED,Ability.MARDOEME)),
    Hjalmar(new Unit("Skellige","Hjalmar",10,1,true,Type.RANGED,null)),
    YoungBerserker(new Unit("Skellige","YoungBerserker",2,3,false,Type.RANGED,Ability.BERSERKER)),
    YoungVidkaarl(new Unit("Skellige","YoungVidkaarl",8,0,false,Type.RANGED,Ability.TIGHT_BOND)),
    LightLongship(new Unit("Skellige","LightLongship",4,3,false,Type.RANGED,Ability.MUSTER)),
    WarLongship(new Unit("Skellige","WarLongship",6,3,false,Type.SIEGE,Ability.TIGHT_BOND)),
    DraigBonDhu(new Unit("Skellige","DraigBonDhu",2,1,false,Type.SIEGE,Ability.COMMANDERS_HORN)),
    BlueboyLugos(new Unit("Skellige","BlueboyLugos",6,1,false,Type.CLOSE,null)),
    ClanTordarrochArmorsmith(new Unit("Skellige","ClanTordarrochArmorsmith",4,1,false,Type.CLOSE,null)),
    HolgerBlackhand(new Unit("Skellige","HolgerBlackhand",4,1,false,Type.SIEGE,null)),
    Olaf(new Unit("Skellige","Olaf",12,1,false,Type.AGILE,Ability.MORAL_BOOST));

    private final Card unit;

    AllUnits(Card unit) {
        this.unit = unit;
    }

    public Card getCard() {
        return unit;
    }
}
